USE HowKteam
GO


CREATE TABLE TESTCHECK
(
	ID INT PRIMARY KEY IDENTITY,
	LUONG INT, 
)
-- INSERT 10000 RECORD
DECLARE @I INT = 0;
DECLARE @N INT = 10000;
DECLARE @SUM INT

WHILE (@I < @N) 
BEGIN
	INSERT TESTCHECK (LUONG) VALUES (@N + @I)
	SET @I+=1
END
SELECT * FROM TESTCHECK
DROP TABLE TESTCHECK 