USE HowKteam
GO

CREATE TABLE TestAuto
(
	ID INT PRIMARY KEY IDENTITY, -- IDENTITY(START, STEP)
	_NAME NVARCHAR(20),
)
GO

INSERT TestAuto (_NAME) VALUES (N'DUONG')
INSERT TestAuto (_NAME) VALUES (N'DUONG')
INSERT TestAuto (_NAME) VALUES (N'DUONG')
INSERT TestAuto (_NAME) VALUES (N'DUONG')
INSERT TestAuto (_NAME) VALUES (N'DUONG')

SELECT * FROM TestAuto
DROP TABLE TestAuto