USE HowKteam
GO

CREATE TABLE TESTCHECK
(
	ID INT PRIMARY KEY IDENTITY,
	LUONG INT --CHECK(LUONG > 3000 AND LUONG < 9000)
	CONSTRAINT CK_LUONG CHECK(LUONG > 3000 AND LUONG < 9000)
)
GO

INSERT TESTCHECK(LUONG) VALUES (4000)
INSERT TESTCHECK(LUONG) VALUES (5000)

SELECT * FROM TESTCHECK

DROP TABLE TESTCHECK
