USE HowKteam
GO

SELECT * FROM GIAOVIEN

SELECT HOTEN, TENBM, LUONG INTO LUONGGIAOVIEN FROM GIAOVIEN, BOMON
WHERE GIAOVIEN.MABM = BOMON.MABM

UPDATE GIAOVIEN SET LUONG = 900
WHERE MAGV = '001'

SELECT * FROM LUONGGIAOVIEN
DROP TABLE LUONGGIAOVIEN

-- => dùng view tạo ra bảng mới dữ liệu tham chiếu tới cũng sẽ thay đỏi nếu bảng góc thay đổi
CREATE VIEW TESTVIEW AS SELECT * FROM GIAOVIEN
SELECT * FROM TESTVIEW
DROP VIEW TESTVIEW

-- UPDATE VIEW
ALTER VIEW TESTVIEW AS SELECT HOTEN FROM GIAOVIEN

-- TẠO VIEW CÓ TÊN TIẾNG VIỆT
CREATE VIEW [LƯƠNG] AS SELECT * FROM GIAOVIEN 
SELECT * FROM [LƯƠNG]