USE HowKteam
GO

-- TRIIGEr sẽ được gọi khi có thao tác thay đổi thông tin trên bảng
-- INSERT | UPDATE | DELETED
-- PRINT KHONG SU DUNG TRONG FUNCTION
CREATE TRIGGER UTG_InsertGiaoVien
ON dbo.GIAOVIEN
FOR INSERT, UPDATE
AS
BEGIN
	ROLLBACK TRAN -- Hủy bỏ thao tác vừa cập nhật dữ liệu 
	PRINT 'TRIGGER'
END

CREATE TRIGGER UTF_AbortOlderThan1 
ON dbo.GIAOVIEN
FOR DELETE
AS
BEGIN
	DECLARE @COUNT INT
	SELECT @COUNT = COUNT(*) FROM DELETED
	WHERE YEAR(GETDATE()) - YEAR(deleted.NGSINH) < 1
	IF(@COUNT > 0) 
	BEGIN
		PRINT N'KH DUOC XOA'
		ROLLBACK TRAN
	END
END

