USE HowKteam
GO


-- 1
CREATE FUNCTION UF_SelectGiaoVien()
RETURNS TABLE
AS RETURN (SELECT * FROM dbo.GIAOVIEN)
GO

SELECT * FROM UF_SelectGiaoVien();

-- 2
CREATE FUNCTION UF_LuongGiaoVien(@MaGv char(10))
RETURNS INT
AS
BEGIN
	DECLARE @LUONG INT 
	SELECT @LUONG = LUONG FROM dbo.GIAOVIEN WHERE @MAGv = MAGV
	RETURN @LUONG
END
GO

SELECT LUONG FROM GIAOVIEN WHERE dbo.UF_LuongGiaoVien('001') = LUONG

-- 3
CREATE FUNCTION UFF_isOdd(@Num INT)
RETURNS NVARCHAR(20)
AS
BEGIN
	DECLARE @MESSAGE NVARCHAR(20)
	IF (@Num % 2 = 0)
		SET @MESSAGE = N'Số chẵn'
	ELSE 
		SET @MESSAGE = N'Số lẽ'
	RETURN @MESSAGE
END
GO

alter FUNCTION UF_AGE(@NgaySinh date) 
RETURNS INT
AS 
BEGIN
	return YEAR(GETDATE()) - YEAR(@NgaySinh)
END
GO

SELECT dbo.UF_AGE(NGSINH), dbo.UFF_isOdd(dbo.UF_AGE(NGSINH)) FROM GIAOVIEN
