USE HowKteam
GO

-- xuất ra số giao viên của từng bộ môn có giáo viên lớn hơn 1 
SELECT BOMON.MABM, COUNT(*) FROM GIAOVIEN, BOMON
WHERE BOMON.MABM = GIAOVIEN.MABM
GROUP BY BOMON.MABM
HAVING COUNT(*) > 1 --(= WHERE NHUNG TRONG GROUP BY)

-- xuất ra mức lương và tổng tuổi của giao viên nhận mức lương đó
-- và có người thân 
SELECT LUONG, SUM(YEAR(GETDATE()) - YEAR(GIAOVIEN.NGSINH)) FROM GIAOVIEN, NGUOITHAN
WHERE GIAOVIEN.MAGV = NGUOITHAN.MAGV
GROUP BY LUONG, GIAOVIEN.NGSINH
HAVING YEAR(GETDATE()) - YEAR(GIAOVIEN.NGSINH) > (SELECT AVG(YEAR(GETDATE()) - YEAR(GIAOVIEN.NGSINH)))
