USE HowKteam
GO

SELECT * FROM dbo.GIAOVIEN, dbo.BOMON
WHERE GIAOVIEN.MABM = BOMON.MABM

SELECT * FROM dbo.GIAOVIEN

-- INNER JOIN + VOI NHUNG THU K NAM TRONG DIEU KIEN(NULL)
SELECT * FROM dbo.GIAOVIEN FULL OUTER JOIN dbo.BOMON
ON GIAOVIEN.MABM = BOMON.MABM

-- CROSS JOIN 
SELECT * FROM dbo.GIAOVIEN CROSS JOIN dbo.BOMON --== SELECT * FROM dbo.GIAOVIEN, dbo.BOMON 