USE HowKteam
GO


-- XUẤT ra thông tin giáo viên 001 mà là gvqlcm
SELECT * FROM dbo.GIAOVIEN 
WHERE MAGV = '003'
AND MAGV IN (SELECT GVQLCM FROM dbo.GIAOVIEN)

-- TRUY VẤN LÒNG TRONG FROM 
SELECT * FROM dbo.GIAOVIEN, (SELECT * FROM dbo.DETAI) AS DT

-- xuât ra thông tin giao viến tham giá nhiều hơn 1 đề tài
SELECT * FROM dbo.GIAOVIEN AS GV
WHERE 1 < 
(SELECT COUNT(*) FROM dbo.THAMGIADT
WHERE THAMGIADT.MAGV = GV.MAGV)

-- xuất ra thông tin của khoa có nhiều hơn 2 giao viên
SELECT * FROM KHOA AS K
WHERE 2 < 
(SELECT COUNT(MAKHOA) FROM dbo.GIAOVIEN, dbo.BOMON
WHERE GIAOVIEN.MABM = BOMON.MABM
AND K.MAKHOA = BOMON.MAKHOA)

--AND BOMON.MAKHOA = KHOA.MAKHOA
SELECT * FROM dbo.BOMON
SELECT * FROM dbo.GIAOVIEN
SELECT * FROM dbo.KHOA

SELECT COUNT(KHOA.MAKHOA) FROM BOMON, GIAOVIEN, KHOA
WHERE GIAOVIEN.MABM = BOMON.MABM
AND BOMON.MAKHOA = KHOA.MAKHOA