USE HowKteam
GO

SELECT * FROM dbo.GIAOVIEN JOIN dbo.BOMON
ON BOMON.MABM = GIAOVIEN.MABM

SELECT * FROM dbo.GIAOVIEN LEFT JOIN dbo.BOMON
ON BOMON.MABM = GIAOVIEN.MABM

SELECT * FROM dbo.GIAOVIEN RIGHT JOIN dbo.BOMON
ON BOMON.MABM = GIAOVIEN.MABM


-- 
SELECT * FROM dbo.BOMON JOIN dbo.GIAOVIEN
ON BOMON.MABM = GIAOVIEN.MABM

SELECT * FROM dbo.BOMON LEFT JOIN dbo.GIAOVIEN
ON BOMON.MABM = GIAOVIEN.MABM

SELECT * FROM dbo.BOMON RIGHT JOIN dbo.GIAOVIEN
ON BOMON.MABM = GIAOVIEN.MABM